In [21]:
import torchaudio
from torchaudio import transforms
from scipy.io import wavfile
import torch
import torch.nn as nn
import torch.nn.functional as F

In [22]:
from model_filter import lowpass_filter, XpassFilter
from misc_tools import MyAudio
from paths import *

In [23]:
wav_filename = train_audio_ + "19/198/19-198-0011.flac"
cut_off_freq = 500

high_off_lower = 4000
high_off_upper = 10000

In [24]:
data, fs = torchaudio.load(wav_filename)

In [25]:
lowfilter = XpassFilter(cut_off_upper=cut_off_freq)

In [26]:
lowout = lowfilter(data, fs)

In [27]:
MyAudio.play_audio_torch(lowout, sample_rate=fs)

In [39]:
cosine_similarity = F.cosine_similarity(lowout, filtered)

In [43]:
lowout

tensor([[-0.0031, -0.0029, -0.0027,  ..., -0.0034, -0.0034, -0.0033]])

In [44]:
filtered

tensor([[-0.0032, -0.0030, -0.0027,  ..., -0.0034, -0.0034, -0.0033]])

- conclusion: numpy and torch code are matching. 

In [40]:
cosine_similarity

tensor([1.0000])

In [28]:
ori = data

In [29]:
MyAudio.play_audio_torch(data, sample_rate=fs)

In [30]:
data = data.squeeze()
data = data.numpy()

In [31]:
filtered = lowpass_filter(data,fs,cut_off_freq)
filtered = torch.tensor(filtered)
filtered = filtered.unsqueeze(0)

In [32]:
MyAudio.play_audio_torch(filtered, sample_rate=fs)

In [33]:
high_filtered = lowpass_filter(data, fs, high_off_upper, high_off_lower)
high_filtered = torch.tensor(high_filtered)
high_filtered = high_filtered.unsqueeze(0)

In [34]:
MyAudio.play_audio_torch(high_filtered, sample_rate=fs)

In [35]:
torchaudio.save("before.wav", ori, sample_rate=fs)

In [36]:
torchaudio.save("after.wav", filtered, sample_rate=fs)