In [1]:
import torch
from torch.utils.data import DataLoader, TensorDataset

In [3]:
# Assuming you have a dataset (features and labels) stored as tensors
features = torch.randn(16, 10)  # Example: 128 samples with 10 features each
labels = torch.randint(0, 2, (16,))  # Example: Binary labels

# Create a PyTorch TensorDataset
dataset = TensorDataset(features, labels)

# Create a DataLoader without shuffling
batch_size = 4
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)
print(labels)

# Iterate through batches
for batch_idx, (batch_features, batch_labels) in enumerate(dataloader):
    # print(f"Batch {batch_idx + 1}: Features shape {batch_features.shape}, Labels shape {batch_labels.shape}")
    print(batch_labels)


tensor([0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0])
tensor([0, 1, 1, 1])
tensor([0, 1, 1, 1])
tensor([0, 1, 0, 0])
tensor([1, 0, 0, 0])


In [1]:
import os
import pickle
from paths import *
from ssd_paths import *

In [2]:
with open(os.path.join(src_, "no-stress-seg.dict"), "rb") as file:
    # Load the object from the file
    mylist = pickle.load(file)